sonar.projectKey=thomasguzmangajardo0_laboratorio-calidad
sonar.organization=thomasguzmangajardo0
sonar.sources=BACKEND/src,FRONTEND/src
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
